<?php
/**
 * Auto-generated whistleblower policy page (Art. 7 + 8 disclosure).
 *
 * @package EuroComply\Whistleblower
 */

declare( strict_types = 1 );

namespace EuroComply\Whistleblower;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class PolicyPageGenerator {

	public static function render() : string {
		$s    = Settings::get();
		$auth = Settings::authorities();
		$cc   = strtoupper( (string) $s['organisation_country'] );
		$row  = $auth[ $cc ] ?? null;

		ob_start();
		echo '<div class="eurocomply-wb-policy">';
		echo '<h2>' . esc_html__( 'Whistleblower policy', 'eurocomply-whistleblower' ) . '</h2>';
		echo '<p>' . esc_html( sprintf(
			/* translators: 1: org 2: country */
			__( '%1$s (%2$s) operates an internal reporting channel pursuant to Directive (EU) 2019/1937 on the protection of persons who report breaches of Union law.', 'eurocomply-whistleblower' ),
			(string) $s['organisation_name'],
			(string) $s['organisation_country']
		) ) . '</p>';

		echo '<h3>' . esc_html__( 'How to report', 'eurocomply-whistleblower' ) . '</h3>';
		$page_id = (int) $s['public_policy_page_id'];
		echo '<ul>';
		echo '<li>' . esc_html__( 'Use the public reporting form on this site (anonymously or with contact details).', 'eurocomply-whistleblower' ) . '</li>';
		echo '<li>' . esc_html( sprintf( /* translators: %s email */ __( 'Email the compliance officer at %s.', 'eurocomply-whistleblower' ), (string) $s['compliance_email'] ) ) . '</li>';
		echo '<li>' . esc_html__( 'Reports may also be submitted to the competent external authority (see below).', 'eurocomply-whistleblower' ) . '</li>';
		echo '</ul>';

		echo '<h3>' . esc_html__( 'What happens after you report', 'eurocomply-whistleblower' ) . '</h3>';
		echo '<ul>';
		echo '<li>' . esc_html( sprintf( /* translators: %d days */ __( 'Acknowledgement within %d days (Art. 9(1)(b)).', 'eurocomply-whistleblower' ), (int) $s['ack_deadline_days'] ) ) . '</li>';
		echo '<li>' . esc_html( sprintf( /* translators: %d days */ __( 'Feedback on action taken within %d days (Art. 9(1)(f)).', 'eurocomply-whistleblower' ), (int) $s['feedback_deadline_days'] ) ) . '</li>';
		echo '<li>' . esc_html__( 'Your identity is confidential and is protected against retaliation (Art. 16, Art. 19).', 'eurocomply-whistleblower' ) . '</li>';
		echo '<li>' . esc_html__( 'Anonymous reporters receive a follow-up token to check status without disclosing identity.', 'eurocomply-whistleblower' ) . '</li>';
		echo '</ul>';

		if ( $row && ! empty( $s['enable_external_referral'] ) ) {
			echo '<h3>' . esc_html__( 'Competent external authority', 'eurocomply-whistleblower' ) . '</h3>';
			echo '<p>';
			printf(
				'<strong>%s</strong> &middot; <a href="mailto:%s">%s</a> &middot; <a href="%s" rel="noopener nofollow" target="_blank">%s</a>',
				esc_html( (string) $row['authority'] ),
				esc_attr( (string) $row['email'] ),
				esc_html( (string) $row['email'] ),
				esc_url( (string) $row['website'] ),
				esc_html( (string) $row['website'] )
			);
			echo '</p>';
		}

		echo '<h3>' . esc_html__( 'Confidentiality and data protection', 'eurocomply-whistleblower' ) . '</h3>';
		echo '<p>' . esc_html__( 'Reports are accessible only to designated recipients. Every access is logged. Personal data is processed under GDPR Art. 6(1)(c) (legal obligation) for the limited purpose of investigating reported breaches.', 'eurocomply-whistleblower' ) . '</p>';

		echo '<p><small>' . esc_html__( 'This policy is generated by EuroComply Whistleblower and reflects Directive (EU) 2019/1937. It does not replace legal advice.', 'eurocomply-whistleblower' ) . '</small></p>';
		echo '</div>';
		return (string) ob_get_clean();
	}

	public static function ensure_page() : int {
		$s   = Settings::get();
		$pid = (int) $s['public_policy_page_id'];
		if ( $pid > 0 && get_post( $pid ) ) {
			return $pid;
		}
		$id = wp_insert_post( array(
			'post_title'   => __( 'Whistleblower policy', 'eurocomply-whistleblower' ),
			'post_content' => '[eurocomply_whistleblower_policy] ' . "\n\n" . '[eurocomply_whistleblower_form]',
			'post_status'  => 'draft',
			'post_type'    => 'page',
		), true );
		if ( is_wp_error( $id ) || ! $id ) {
			return 0;
		}
		$s['public_policy_page_id'] = (int) $id;
		update_option( Settings::OPTION_KEY, $s, false );
		return (int) $id;
	}
}
